name: uikit2swiftui

options:
  bundleIdPrefix: uikit2swiftui.hrfmmr.com
  deploymentTarget:
    iOS: 14.0

targets:
  app:
    type: application
    platform: iOS
    sources:
      - app
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.hrfmmr.uikit2swiftui"
        PRODUCT_NAME: uikit2swiftui
    dependencies:
      - package: NeedleFoundation
        product: NeedleFoundation
    preBuildScripts:
      - name: Generate resolving dependencies code
        script: |
          cd "$PROJECT_DIR"
          if [ -f ".envrc" ]; then
            source ".envrc"
          fi
          make needle

packages:
  NeedleFoundation:
    url: https://github.com/uber/needle
    from: 0.19.0
